CREATE TABLE tasks
(
id BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
summary VARCHAR(256) NOT NULL,
description TEXT,
status VARCHAR(256) NOT NULL,
user_id VARCHAR(256) NOT NULL
);

CREATE TABLE users
(
id VARCHAR(256) NOT NULL PRIMARY KEY,
username VARCHAR(256) NOT NULL,
password VARCHAR(256) NOT NULL,
authority VARCHAR(256) NOT NULL
);